import gsap, {
    CSSRulePlugin,
    CustomBounce,
    CustomEase,
    CustomWiggle,
    Draggable,
    DrawSVGPlugin,
    EaselPlugin,
    EasePack,
    Flip,
    GSDevTools,
    InertiaPlugin,
    MorphSVGPlugin,
    MotionPathPlugin,
    Observer,
    Physics2DPlugin,
    PhysicsPropsPlugin,
    PixiPlugin,
    ScrambleTextPlugin,
    ScrollSmoother,
    ScrollToPlugin,
    ScrollTrigger,
    SplitText,
    TextPlugin
} from "gsap/all";

gsap.registerPlugin(
    CSSRulePlugin,
    CustomBounce,
    CustomEase,
    CustomWiggle,
    Draggable,
    DrawSVGPlugin,
    EaselPlugin,
    EasePack,
    Flip,
    GSDevTools,
    InertiaPlugin,
    MorphSVGPlugin,
    MotionPathPlugin,
    Observer,
    Physics2DPlugin,
    PhysicsPropsPlugin,
    PixiPlugin,
    ScrambleTextPlugin,
    ScrollSmoother,
    ScrollToPlugin,
    ScrollTrigger,
    SplitText,
    TextPlugin
);

export { gsap };

export {
    CSSRulePlugin,
    CustomBounce,
    CustomEase,
    CustomWiggle,
    Draggable,
    DrawSVGPlugin,
    EaselPlugin,
    EasePack,
    Flip,
    GSDevTools,
    InertiaPlugin,
    MorphSVGPlugin,
    MotionPathPlugin,
    Observer,
    Physics2DPlugin,
    PhysicsPropsPlugin,
    PixiPlugin,
    ScrambleTextPlugin,
    ScrollSmoother,
    ScrollToPlugin,
    ScrollTrigger,
    SplitText,
    TextPlugin
};

